version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-flow-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: dev-flow-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
